[package]
name = "ink-rs"
version = "0.1.0"
edition.workspace = true
description = "Rust implementation and language fork of Ink for interactive narratives."
documentation = "https://docs.rs/ink-rs"
repository.workspace = true
readme = "README.md"
keywords.workspace = true
include = [
    "/Cargo.toml",
    "/README.md",
    "/src/**",
    "/docs/Architecture.md",
    "/docs/SyntaxReference.md",
    "/docs/ink_JSON_runtime_format.md",
]

[lib]
doctest = false
test = false

[features]
default = ["runtime"]
runtime = ["dep:ink-runtime"]
compiler = ["dep:ink-compiler", "format"]
format = ["dep:ink-story-json-format"]
full = ["runtime", "compiler"]

[dependencies]
ink-runtime = { version = "1.2.1", path = "crates/ink-runtime", optional = true }
ink-compiler = { version = "0.1.0", path = "crates/ink-compiler", optional = true }
ink-story-json-format = { version = "0.1.0", path = "crates/ink-story-json-format", optional = true }

[workspace]
members = [
    "crates/ink-compiler",
    "crates/ink-story-json-format",
    "crates/ink-runtime",
    "crates/ink-experiments",
    "crates/ink-test",
    "crates/ink-tools",
]
default-members = [
    ".",
    "crates/ink-compiler",
    "crates/ink-story-json-format",
    "crates/ink-runtime",
    "crates/ink-experiments",
    "crates/ink-test",
    "crates/ink-tools",
]
resolver = "2"

[workspace.package]
edition = "2021"
repository = "https://github.com/xumingthepoet/ink-rs"
keywords = ["ink", "interactive-fiction", "narrative", "game"]

[profile.dev]
opt-level = 0
debug = 0
codegen-units = 256
