//! A generated [`Choice`] from the story.
use core::fmt;
use std::cell::RefCell;

use crate::{
    callstack::Continuation,
    object::{Object, RTObject},
    path::Path,
};

/// Represents a choice generated by a [`Story`](crate::story::Story).
#[derive(Clone)]
pub struct Choice {
    obj: Object,
    continuation_at_generation: RefCell<Option<Continuation>>,
    pub(crate) target_path: Path,
    pub(crate) is_invisible_default: bool,
    /// ink-rs tags attached to this `Choice`.
    pub tags: Vec<String>,
    /// The original index into the current choice list on the [`Story`](crate::story::Story) when
    /// this `Choice` was generated, for convenience.
    pub index: RefCell<usize>,
    /// The main text to present to the player for this `Choice`.
    pub text: String,
}

impl Choice {
    pub(crate) fn new(
        target_path: Path,
        is_invisible_default: bool,
        tags: Vec<String>,
        continuation_at_generation: Continuation,
        text: String,
    ) -> Choice {
        Self {
            obj: Object::new(),
            target_path,
            is_invisible_default,
            tags,
            index: RefCell::new(0),
            text,
            continuation_at_generation: RefCell::new(Some(continuation_at_generation)),
        }
    }

    pub(crate) fn get_continuation_at_generation(&self) -> Option<Continuation> {
        self.continuation_at_generation
            .borrow()
            .as_ref()
            .map(|t| t.clone())
    }
}

impl RTObject for Choice {
    fn get_object(&self) -> &Object {
        &self.obj
    }
}

impl fmt::Display for Choice {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "**Choice**")
    }
}
