[package]
name = "ink-runtime"
version = "1.2.1"
edition.workspace = true
description = "Runtime story engine for ink-rs interactive narratives."
documentation = "https://docs.rs/ink-runtime"
repository.workspace = true
keywords.workspace = true
include = ["/Cargo.toml", "/src/**"]

[dependencies]
ink-story-json-format = { version = "0.1.0", path = "../ink-story-json-format" }
serde_json = "1.0.93"
strum = { version = "0.27.2", features = ["derive"] }
as-any = "0.3.0"
rand = "0.9.2"
web-time = "1.1.0"

[target.'cfg(all(target_family = "wasm", target_os = "unknown"))'.dependencies]
getrandom = { version = "0.3.3", features = ["wasm_js"] }
